export default {
  Acura: ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
  "Alfa Romeo": [
    "4C",
    "Giulia",
    "Stelvio",
    "C4",
    "Tonale",
    "Giulietta",
    "Mito",
  ],
  "AM General": ["Humvee", "Hummer H1", "Hummer HMMWV"],
  "Aston Martin": [
    "DB11",
    "DBS Superleggera",
    "Vantage",
    "Rapide",
    "DBX",
    "Valhalla",
    "Valkyrie",
    "Virage",
    "One-77",
    "DBS",
    "DB9",
    "Vanquish",
    "Lagonda",
    "Cygnet",
    "DB5",
    "DB6",
    "DB4",
  ],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "TT",
    "SQ5",
    "SQ7",
    "SQ8",
  ],
  Bentley: [
    "Bentayga",
    "Continental GT",
    "Continental Flying Spur",
    "Mulsanne",
    "Bentayga Hybrid",
    "Bentley Arnage",
    "Azure",
    "Brooklands",
    "Turbo R",
    "Eight",
    "Mulsanne Turbo",
    "Continental Flying Spur Speed",
    "Continental R",
    "Continental T",
    "Continental SC",
    "Azure T",
  ],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "iX",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "Z4 M",
  ],
  Buick: [
    "Enclave",
    "Encore",
    "Envision",
    "LaCrosse",
    "Regal",
    "Regal TourX",
    "Buick Cascada",
    "Century",
    "Electra",
    "LeSabre",
    "Lucerne",
    "Park Avenue",
    "Rainier",
    "Reatta",
    "Rendezvous",
    "Terraza",
    "Verano",
  ],
  Cadillac: [
    "CT4",
    "CT5",
    "CT6",
    "Escalade",
    "XT4",
    "XT5",
    "XT6",
    "ATS",
    "Catera",
    "CTS",
    "DTS",
    "Eldorado",
    "Seville",
    "SRX",
    "STS",
    "XLR",
  ],
  Chevrolet: [
    "Blazer",
    "Camaro",
    "Corvette",
    "Equinox",
    "Impala",
    "Malibu",
    "Silverado",
    "Spark",
    "Suburban",
    "Tahoe",
    "Trailblazer",
    "Traverse",
    "Trax",
    "Bolt EV",
    "Chevrolet Avalanche",
    "Aveo",
    "Cavalier",
    "Chevelle",
    "Cobalt",
    "Colorado",
    "Cruze",
    "Express",
    "HHR",
    "Lumina",
    "Monte Carlo",
    "S-10",
    "Sonic",
    "SS",
    "Chevrolet SSR",
    "Tracker",
    "Venture",
    "Volt",
  ],
  Chrysler: [
    "300",
    "Voyager",
    "Pacifica",
    "Aspen",
    "Concorde",
    "Crossfire",
    "LHS",
    "PT Cruiser",
    "Sebring",
    "Town & Country",
  ],
  Dodge: [
    "Challenger",
    "Charger",
    "Durango",
    "Journey",
    "Caravan",
    "Dakota",
    "Dart",
    "Grand Caravan",
    "Intrepid",
    "Magnum",
    "Neon",
    "Nitro",
    "Ram",
    "SRT Viper",
    "Stealth",
    "Stratus",
    "Viper",
  ],
  Ferrari: [
    "488",
    "812 Superfast",
    "F8 Tributo",
    "Portofino",
    "Roma",
    "SF90 Stradale",
    "California",
    "F430",
    "LaFerrari",
    "Enzo",
    "458 Italia",
    "599",
    "360 Modena",
    "F355",
    "Testarossa",
    "F40",
    "288 GTO",
    "308 GTB",
    "250 GTO",
    "166 Inter",
  ],
  FIAT: ["500", "500X", "500L", "124 Spider", "FIAT 500e"],
  Ford: [
    "Bronco",
    "Escape",
    "Expedition",
    "Explorer",
    "F-150",
    "Mustang",
    "Ranger",
    "Mach-E",
    "Ford GT",
    "C-Max",
    "Edge",
    "Excursion",
    "Fiesta",
    "Flex",
    "Focus",
    "Freestar",
    "Freestyle",
    "Probe",
    "Taurus",
    "Thunderbird",
    "Transit",
    "Windstar",
  ],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  GMC: [
    "Acadia",
    "Canyon",
    "Sierra",
    "Terrain",
    "Yukon",
    "GMC Acadia Limited",
    "Canyon Hybrid",
    "Envoy",
    "Jimmy",
    "Safari",
    "Savana",
    "Sonoma",
    "Typhoon",
    "GMC Vandura",
    "GMC Sprint",
    "GMC Syclone",
  ],
  Honda: [
    "Accord",
    "Civic",
    "Clarity",
    "CR-V",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Ridgeline",
    "CRX",
    "Element",
    "FCX Clarity",
    "Prelude",
    "S2000",
  ],
  HUMMER: [
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "H7",
    "H8",
    "H9",
    "H10",
    "H11",
    "H12",
    "H13",
    "H14",
    "H15",
  ],
  Hyundai: [
    "Accent",
    "Elantra",
    "Ioniq",
    "Kona",
    "Palisade",
    "Santa Fe",
    "Sonata",
    "Tucson",
    "Veloster",
    "Venue",
    "Hyundai Azera",
    "Entourage",
    "Equus",
    "Genesis",
    "Santa Cruz",
    "Tiburon",
    "Veracruz",
    "XG300",
    "XG350",
  ],
  Isuzu: [
    "MU-X",
    "D-MAX",
    "Ascender",
    "Axiom",
    "Hombre",
    "Impulse",
    "Oasis",
    "Rodeo",
    "Stylus",
    "Trooper",
    "VehiCROSS",
  ],
  Jaguar: [
    "E-PACE",
    "F-PACE",
    "F-TYPE",
    "I-PACE",
    "XE",
    "XF",
    "XJ",
    "Jaguar C-Type",
    "D-Type",
    "E-Type",
    "S-Type",
    "X-Type",
    "XK",
    "XKR",
  ],
  Jeep: [
    "Cherokee",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Renegade",
    "Wrangler",
    "Jeep CJ",
    "Grand Wagoneer",
    "Wagoneer",
  ],

  Kia: [
    "Cadenza",
    "Forte",
    "K5",
    "Niro",
    "Optima",
    "Rio",
    "Seltos",
    "Sorento",
    "Soul",
    "Sportage",
    "Stinger",
    "Telluride",
    "Amanti",
    "Borrego",
    "K900",
    "Mohave",
    "Rondo",
  ],
  Lamborghini: [
    "Aventador",
    "Huracán",
    "Urus",
    "Countach",
    "Diablo",
    "Gallardo",
    "Murciélago",
    "Reventón",
    "Sesto Elemento",
    "Veneno",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Land Rover Series I",
    "Series II",
    "Series III",
  ],
  Lexus: [
    "ES",
    "GX",
    "IS",
    "LC",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "UX",
    "LFA",
    "HS",
    "IS F",
    "RC F",
    "SC 430",
  ],
  Lincoln: [
    "Aviator",
    "Continental",
    "Corsair",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Lincoln Blackwood",
    "Capri",
    "LS",
    "Mark LT",
    "MKC",
    "MKS",
    "MKT",
    "MKT Town Car",
    "MKS Town Car",
    "MKX",
    "MKZ Hybrid",
    "Town Car",
    "Zephyr",
  ],

  Lotus: [
    "Elise",
    "Evora",
    "Exige",
    "Esprit",
    "Europa",
    "Cortina",
    "Seven",
    "Elite",
    "Eclat",
    "Excel",
    "Talbot Sunbeam Lotus",
  ],
  Lucid: [
    "Air",
    "Air Dream Edition",
    "Gravity",
    "Project Gravity",
    "Imagine",
    "Project Imagine",
    "Xeno",
    "Project Xeno",
    "Atmos",
    "Project Atmos",
    "Resonance",
    "Project Resonance",
    "Spectre",
    "Project Spectre",
  ],
  Maserati: [
    "Ghibli",
    "Levante",
    "Quattroporte",
    "GranTurismo",
    "GranCabrio",
    "Maserati 3200 GT",
    "4200 GT",
    "GranSport",
    "Spyder",
    "Shamal",
  ],
  Maybach: ["S-Class", "GLS", "57", "62", "Exelero"],
  Mazda: [
    "CX-3",
    "CX-5",
    "CX-9",
    "Mazda3",
    "Mazda6",
    "MX-5 Miata",
    "Mazda2",
    "Mazda5",
    "Mazda8",
    "Mazda MX-6",
    "Mazda RX-7",
    "Mazda RX-8",
    "Mazda R360",
    "Mazda Carol",
    "Mazda Luce",
    "Mazda Roadpacer",
  ],
  McLaren: [
    "540C",
    "570S",
    "600LT",
    "620R",
    "675LT",
    "720S",
    "Artura",
    "Elva",
    "GT",
    "P1",
    "Sabre",
    "Speedtail",
    "McLaren GT",
    "MP4-12C",
    "MP4-31",
    "M6A",
    "M7A",
    "M8A",
    "M8D",
    "M9A",
    "M10A",
    "M11A",
    "M12",
    "M14A",
    "M14D",
    "M15",
    "M16",
    "M20",
    "M23",
    "M26",
    "M29",
    "M30",
    "MCL35M",
  ],
  "Mercedes-Benz": [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "SLC",
    "SL",
    "SLS AMG",
    "AMG GT",
    "G-Class",
    "Metris",
    "Sprinter",
    "190",
    "200",
    "220",
    "230",
    "260",
    "280",
    "300",
    "320",
    "400",
    "420",
    "500",
    "560",
    "600",
    "E 55 AMG",
    "E 63 AMG",
    "SLK 55 AMG",
    "SLC 43 AMG",
    "SLK 230",
    "SLK 320",
    "SLK 350",
    "SLR McLaren",
    "Vario",
    "Viano",
    "Vito",
  ],
  Mercury: [
    "Grand Marquis",
    "Mariner",
    "Milan",
    "Mountaineer",
    "Capri",
    "Cougar",
    "Marauder",
    "Monarch",
    "Montego",
    "Monterey",
    "Mystique",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
  ],
  MINI: [
    "Clubman",
    "Convertible",
    "Countryman",
    "Hardtop",
    "Cooper",
    "Cooper S",
    "Cooper Countryman",
    "Cooper Paceman",
    "Cooper Roadster",
  ],
  Mitsubishi: [
    "Eclipse Cross",
    "Outlander",
    "Outlander Sport",
    "3000GT",
    "Diamante",
    "Eclipse",
    "Endeavor",
    "Expo",
    "Galant",
    "Lancer",
    "Mighty Max",
    "Mirage",
    "Montero",
    "Montero Sport",
    "Outlander PHEV",
    "Raider",
    "Sigma",
    "Starion",
    "Tredia",
  ],
  Nissan: [
    "370Z",
    "Altima",
    "Armada",
    "GT-R",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "NV Cargo",
    "NV Passenger",
    "NV200",
    "Pathfinder",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Titan",
    "Versa",
    "Nissan 200SX",
    "240SX",
    "300ZX",
    "350Z",
    "Cube",
    "Juke",
    "Lucino",
    "NX",
    "Pulsar",
    "Quest",
    "Rogue Select",
    "Rogue Select Krom",
    "Rogue Select S Krom",
    "Rogue S Krom",
    "Versa Krom",
    "Xterra",
    "Rogue S",
  ],

  Plymouth: [
    "Barracuda",
    "Duster",
    "Fury",
    "GTX",
    "Prowler",
    "Road Runner",
    "Satellite",
    "Superbird",
    "Volare",
    "Acclaim",
    "Breeze",
    "Colt",
    "Gran Fury",
    "Horizon",
    "Laser",
    "Neon",
    "Plymouth Reliant",
    "Sapporo",
    "Sundance",
    "Voyager",
  ],
  Polestar: ["2", "Polestar 1"],
  Pontiac: [
    "Aztek",
    "Bonneville",
    "Catalina",
    "Fiero",
    "Firebird",
    "G3",
    "G5",
    "G6",
    "G8",
    "Grand Am",
    "Grand Prix",
    "GTO",
    "Montana",
    "Solstice",
    "Sunfire",
    "Torrent",
    "Vibe",
    "Pontiac 6000",
    "Pontiac Astre",
    "Pontiac Chieftain",
    "Pontiac Executive",
    "Pontiac Grand Safari",
    "Pontiac Grand Ville",
    "Pontiac GTO Judge",
    "Pontiac J2000",
    "Pontiac LeMans",
    "Pontiac Montana SV6",
    "Pontiac Parisienne",
    "Pontiac Phoenix",
    "Pontiac Safari",
    "Pontiac Star Chief",
    "Pontiac Streamliner",
    "Pontiac Sunbird",
    "Pontiac T1000",
    "Pontiac Tempest",
    "Pontiac Trans Sport",
  ],
  Porsche: [
    "911",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "718 Boxster",
    "718 Cayman",
  ],
  Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],

  "Rolls-Royce": [
    "Cullinan",
    "Dawn",
    "Ghost",
    "Phantom",
    "Wraith",
    "Sweptail",
    "Silver Ghost",
    "Silver Seraph",
    "Silver Spur",
    "Park Ward",
    "Camargue",
    "Corniche",
    "Silver Cloud",
    "Silver Shadow",
    "Silver Wraith",
  ],
  Saturn: ["Aura", "Outlook", "Relay", "Sky", "Vue"],
  Scion: ["FR-S", "iA", "iM", "tC", "xB", "xD"],

  Subaru: [
    "Ascent",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Legacy",
    "Outback",
    "Subaru 360",
    "Alcyone SVX",
    "Baja",
    "BRAT",
    "Justy",
    "Leone",
    "Rex",
    "Sambar",
    "Traviq",
    "Trezia",
    "Vivio",
  ],
  Suzuki: [
    "Grand Vitara",
    "Kizashi",
    "SX4",
    "XL7",
    "Aerio",
    "Alto",
    "Cappuccino",
    "Celerio",
    "Equator",
    "Forenza",
    "Fronte",
    "Ignis",
    "Jimny",
    "Kei",
    "Liana",
    "Mighty Boy",
    "Palette",
    "Splash",
    "Swift",
    "SX4 S-Cross",
    "Verona",
    "Wagon R",
    "X-90",
    "Every",
    "Carry",
    "Vitara",
  ],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck", "Roadster"],
  Toyota: [
    "4Runner",
    "Avalon",
    "C-HR",
    "Camry",
    "Corolla",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Tacoma",
    "Tundra",
    "Venza",
    "Yaris",
    "Toyota 86",
    "Auris",
    "Avanza",
    "Avensis",
    "Aygo",
    "Crown",
    "Century",
    "Granvia",
    "Harrier",
    "Hilux",
    "iQ",
    "Kluger",
    "Mark X",
    "Mirai",
    "Previa",
    "Sienta",
    "Soarer",
    "Supra",
    "Tercel",
    "Verso",
    "Vios",
    "Wish",
    "Zelas",
  ],
  Volkswagen: [
    "Arteon",
    "Atlas",
    "Beetle",
    "CC",
    "Golf",
    "Jetta",
    "Passat",
    "Tiguan",
    "Touareg",
    "ID.4",
    "Volkswagen Amarok",
    "Arteon Shooting Brake",
    "Beetle Dune",
    "Beetle R-Line",
    "California",
    "Caravelle",
    "CC R-Line",
    "Crafter",
    "Eos",
    "Fox",
    "Golf Alltrack",
    "Golf GTI",
    "Golf R",
    "Golf SportWagen",
    "ID.3",
    "ID. Buzz",
    "ID. Vizzion",
    "ID. Space Vizzion",
    "Karmann Ghia",
    "Lupo",
    "Microbus",
    "Passat Alltrack",
    "Phaeton",
    "Polo",
    "Santana",
    "Sharan",
    "T-Cross",
    "T-Roc",
    "Taos",
    "Tiguan Allspace",
    "Touareg R",
    "Touran",
    "Up!",
  ],
  Volvo: [
    "S60",
    "S90",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC90",
    "C30",
    "C70",
    "V40",
    "V50",
    "V70",
    "XC70",
    "S40",
    "S70",
    "S80",
    "850",
    "940",
    "960",
    "S90 Twin Engine",
    "V60 Cross Country",
    "V90 Cross Country",
    "XC40 Recharge",
    "XC60 Recharge",
    "XC90 Recharge",
    "P1800",
    "PV444",
    "PV544",
    "Amazon",
    "Duett",
    "P121",
    "P122",
    "P130",
    "P220",
    "240",
    "260",
    "440",
    "460",
    "480",
    "740",
    "760",
    "780",
    "850 R",
    "940SE",
    "960 Royal",
    "C70 Convertible",
    "S40 R-Design",
    "S60 Cross Country",
    "S80 Executive",
    "XC70 Ocean Race",
    "XC90 Ocean Race",
    "C70 Inscription",
  ],
};
